-- Create builder_contacts table for central builder-linked contacts
create table if not exists builder_contacts (
  id bigint generated by default as identity primary key,
  builder_id bigint not null references builders(id) on delete cascade,
  name text not null,
  title text,
  email text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_builder_contacts_builder_id on builder_contacts(builder_id);
